id: 510f63625c03450eb9a89073c813f166
initial_creation_type: ocr
source_metadata:
  volumes:
    487bdedf945646e7a303323f33bb395c:
      base_file: v066.txt
      image_group_id: I1PD95912
      title: འཕགས་པ་འདའ་ཀ་ཡེ་ཤེས་ཞེས་བྱ་བ་ཐེག་པ་ཆེན་པོའི་མདོའི་འགྲེལ་པ།
      total_pages: 1529
      volume_number: 67
